### PR TITLE
Changed pointcloud display in rviz from intensity to range

### PR DESCRIPTION
**Pull request by shaun-edwards**
By default the point cloud rainbow coloring is set to intensity.  A better setting may be the range (x) since the IFM sensor can be thought of more as a range sensor (i.e. not a colored pointcloud).

### CODE REVIEW

**Comment by tpanzarella** [comment]
Your point is well taken Shaun. Maybe we should consider a way to parameterize the launch file to allow for dynamically setting this value with override available on the command line? I find both colorings (i.e., x-range and intensity) useful depending upon what I am trying to do. The original choice to show the intensity was simply to make available the "4'th dimension" of data that are available in this data structure visibly on the screen. Coloring via x-range, by default, on a 3D render seemed redundant while effectively hiding the available intensity data.

**Comment by shaun-edwards** [comment]
I'm certainly on the fence.  The problem I had is that I was looking at planar objects with bar-codes on them.  In the intensity image, it shows up the same color but with artifacts around the bar-code.  Because I assumed I was looking at range, I thought this was an issue with the camera.  While I agree with your thought on showing the 4th dimension, I've never found the intensity information very useful.  It doesn't have an obvious physical meaning, like color for example.  I'm not aware of any PCL (or other methods) that utilize intensity in a meaningful way.  Perhaps I'm just ignorant of the value (and maybe I should have paid more attention when looking at the rviz display).

**Comment by tpanzarella** [comment]
I've seen quite a few applications in industrial settings that introduce things like retroreflectors into the environment to help simplify a segmentation task. Using that as an example, running a binary filter on the intensity channel of the point cloud (i.e., decimating the data based on an intensity threshold) typically yields a significantly more simplified segmentation problem and if your application allows for such artificial beacons, the overall system becomes more robust.

The point of the above comment is to simply provide one example of where the intensity data can be useful. Thinking more about the issue at hand, I think the right thing to do is to parameterize the launch file in a way that allows for choice with sensible defaults. I am currently working on some updates to [libo3d3xx](https://github.com/lovepark/libo3d3xx) that I hope to push out early next week but after that, I can take a stab at parameterizing the launch file as we have been discussing ... that is, if you don't get to it first :-)

**Comment by tpanzarella** [comment]
I just committed to the master branch a means of parameterizing the rviz launch file to color the point cloud by intensity (the default) or x-range. To color by intensity (as before):

    $ roslaunch o3d3xx rviz.launch

To color by x-range:

    $ roslaunch o3d3xx rviz.launch range:=1

To that end, I'm going to close out this pull request since I think we now have the desired functionality without losing the existing functionality.

**Pull request closed without merging**
